name: Deploy WebGL
on:
  push:
    branches: [ main ]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true # <--- This fixes the LFS pointer issue automatically

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.' # Change this if your build is in a subfolder

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
